services:
  jupyter:
    build: 
      context: .
      args:
        DIR_WORK: "/work"
        DIR_MFAPY: "mfapy"
        REQ_TXT: "requirements.txt"
    image: biobr131/mfapy-jupyter:latest
    container_name: jupyter
    command: jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''
    ports:
     - "8888:8888"
    volumes:
     - ./scripts:/work/scripts
    tty: true
    stdin_open: true
